# config.yaml
cricapi:
  base_url: "https://api.cricapi.com/v1/"
  api_key: ${CRICAPI_KEY}

cricbuzz:
  base_url: "https://cricbuzz-cricket.p.rapidapi.com"
  headers:
    x-rapidapi-host: "cricbuzz-cricket.p.rapidapi.com"
    x-rapidapi-key: "${CRICBUZZ_API_KEY}"

